// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/lockscreen": {
    params: {};
  };
  "/desktop": {
    params: {};
  };
  "/hero": {
    params: {};
  };
  "/apps/paint": {
    params: {};
  };
  "/fullcontact": {
    params: {};
  };
  "/off": {
    params: {};
  };
  "/terminal": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/lockscreen" | "/desktop" | "/hero" | "/apps/paint" | "/fullcontact" | "/off" | "/terminal";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/signin.tsx": {
    id: "routes/signin";
    page: "/signin";
  };
  "routes/lockscreen.tsx": {
    id: "routes/lockscreen";
    page: "/lockscreen";
  };
  "routes/desktop.tsx": {
    id: "routes/desktop";
    page: "/desktop";
  };
  "routes/hero.tsx": {
    id: "routes/hero";
    page: "/hero";
  };
  "routes/paint.tsx": {
    id: "routes/paint";
    page: "/apps/paint";
  };
  "routes/fullcontact.tsx": {
    id: "routes/fullcontact";
    page: "/fullcontact";
  };
  "routes/off.tsx": {
    id: "routes/off";
    page: "/off";
  };
  "./apps/terminal/index.ts": {
    id: "apps/terminal/index";
    page: "/terminal";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/signin": typeof import("./app/routes/signin.tsx");
  "routes/lockscreen": typeof import("./app/routes/lockscreen.tsx");
  "routes/desktop": typeof import("./app/routes/desktop.tsx");
  "routes/hero": typeof import("./app/routes/hero.tsx");
  "routes/paint": typeof import("./app/routes/paint.tsx");
  "routes/fullcontact": typeof import("./app/routes/fullcontact.tsx");
  "routes/off": typeof import("./app/routes/off.tsx");
  "apps/terminal/index": typeof import("./app/./apps/terminal/index.ts");
};